const fs = require('fs');

let content = fs.readFileSync('server/prisma/seed-ai4cris.ts', 'utf8');

const submissionHtml = `<div class="space-y-8"><div class="bg-white rounded-3xl p-8 lg:p-12 border border-rule shadow-sm"><p class="text-[16px] text-slate leading-relaxed indent-8">Hội thảo AI4CRIS do Học viện Kỹ thuật mật mã chủ trì phối hợp với FISU Việt Nam, Học viện Báo chí và Tuyên truyền và Tạp chí An toàn thông tin tổ chức cùng với sự bảo trợ của Ban Cơ yếu Chính phủ, Bộ Khoa học và Công nghệ, Hội tin học Việt Nam và Trung tâm Dữ liệu Quốc Gia. Hội thảo là diễn đàn trao đổi học thuật và thực tiễn về ứng dụng trí tuệ nhân tạo trong an toàn thông tin, an ninh mạng và bảo vệ dữ liệu. Sự kiện nhằm cập nhật xu hướng công nghệ, chính sách và các giải pháp trí tuệ nhân tạo tiên tiến, đồng thời kết nối cơ quan quản lý, nhà khoa học, doanh nghiệp và cơ sở đào tạo để thúc đẩy nghiên cứu, hợp tác và chuyển giao công nghệ phục vụ bảo vệ không gian số quốc gia.</p><p class="text-[16px] text-slate leading-relaxed indent-8 mt-4">Ban Tổ chức trân trọng kính mời các nhà nghiên cứu, giảng viên, chuyên gia, cán bộ quản lý, nghiên cứu sinh, học viên và doanh nghiệp gửi bài báo cáo khoa học tham gia các phiên chuyên đề của Hội thảo.</p></div></div>`;

const programHtml = `<div class="space-y-16" style="font-family: var(--font-body)"><section><h2 class="text-[24px] font-bold text-ink mb-6 bg-paper px-4 py-3 rounded-lg border-l-4 border-cipher">1. Phiên toàn thể và bàn tròn (Địa điểm: Hội trường)</h2><div class="overflow-x-auto rounded-xl border border-rule shadow-sm"><table class="w-full text-left border-collapse"><thead><tr class="bg-warm text-ink text-[17px]"><th class="p-4 border-b border-rule w-[140px] whitespace-nowrap">Thời gian</th><th class="p-4 border-b border-rule">Nội dung</th><th class="p-4 border-b border-rule w-[250px]">Diễn giả/Đơn vị</th></tr></thead><tbody class="text-[16px] text-slate divide-y divide-rule"><tr class="hover:bg-paper/50 transition-colors"><td class="p-4 font-semibold text-ink">07:30 - 08:00</td><td class="p-4">Đón tiếp, đăng ký đại biểu</td><td class="p-4">Học viện Kỹ thuật mật mã</td></tr><tr class="hover:bg-paper/50 transition-colors"><td class="p-4 font-semibold text-ink">08:00 - 08:15</td><td class="p-4">Phát biểu Chào mừng và Khai mạc hội thảo</td><td class="p-4">Lãnh đạo Ban Cơ yếu Chính phủ/ Học viện KTMM, Chủ tịch FISU VN</td></tr></tbody></table></div></section></div>`;

const venueHtml = `<div class="grid grid-cols-1 lg:grid-cols-2 gap-12"><div class="space-y-8" style="font-family: var(--font-body)"><section class="bg-paper p-8 rounded-2xl border border-rule"><h2 class="text-[24px] font-bold text-ink mb-6">📍 Địa điểm tổ chức</h2><p class="text-[18px] font-semibold text-ink mb-2">Học viện Kỹ thuật mật mã</p><p class="text-[18px] text-slate">141 Chiến Thắng, Thanh Liệt, Hà Nội</p></section></div><div class="h-full min-h-[400px] rounded-2xl overflow-hidden border border-rule shadow-sm"><iframe src="https://maps.google.com/maps?q=141%20Chi%E1%BA%BFn%20Th%E1%BA%AFng,%20T%C3%A2n%20Tri%E1%BB%81u,%20Thanh%20Tr%C3%AC,%20H%C3%A0%20N%E1%BB%99i,%20Vi%E1%BB%87t%20Nam&t=m&z=15&output=embed&iwloc=near" width="100%" height="100%" style="border: 0; min-height: 400px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></div>`;

const registrationHtml = `<div class="space-y-8" style="font-family: var(--font-body)"><p class="text-[16px] text-slate leading-relaxed">Để tham dự Hội thảo, vui lòng thực hiện đăng ký trực tuyến thông qua biểu mẫu Google Form của Ban Tổ chức.</p><div class="flex flex-col items-center justify-center p-8 bg-white rounded-2xl border border-cipher/20 shadow-sm gap-4"><a href="https://forms.gle/your-google-form-link-here" target="_blank" rel="noopener noreferrer" class="px-8 py-4 rounded-xl bg-cipher text-white font-bold text-[18px] hover:bg-cipher/90 transition-colors shadow-md hover:shadow-lg">👉 Đăng ký tham dự tại đây</a></div></div>`;

content = content.replace(/contentHtml: "<p>Ban Tổ chức trân trọng kính mời các nhà nghiên cứu.*?<\/p>"/, 'contentHtml: `' + submissionHtml + '`');
content = content.replace(/contentHtml: "<p>Chương trình chi tiết sẽ được thông báo sau.<\/p>"/, 'contentHtml: `' + programHtml + '`');
content = content.replace(/contentHtml: "<p><strong>Học viện Kỹ thuật mật mã<\/strong><br\/>141 Chiến Thắng, Thanh Liệt, Hà Nội<\/p>"/, 'contentHtml: `' + venueHtml + '`');
content = content.replace(/contentHtml: "<p>Thông tin đăng ký tham dự sẽ được cập nhật sớm.<\/p>"/, 'contentHtml: `' + registrationHtml + '`');

fs.writeFileSync('server/prisma/seed-ai4cris.ts', content);
